/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesframebarubet;

import Connection.connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Fauzan
 */
public class formPerbaikan extends javax.swing.JFrame {

    /**
     * Creates new form formPerbaikan
     */
    public formPerbaikan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idReceiveReport = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        namaPL = new javax.swing.JLabel();
        tglMain = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btSudah = new javax.swing.JRadioButton();
        btBelum = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Pekerja Lapangan");

        jLabel3.setText("Set Tanggal Maintenance");

        idReceiveReport.setText(".");

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jLabel1.setText("IdReceiveReport");

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        namaPL.setText(".");

        tglMain.setText(".");

        jLabel7.setText("Perbaikan");

        buttonGroup1.add(btSudah);
        btSudah.setText("Sudah");

        buttonGroup1.add(btBelum);
        btBelum.setText("Belum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(simpan)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaPL)
                                    .addComponent(idReceiveReport)
                                    .addComponent(tglMain))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSudah)
                                .addGap(18, 18, 18)
                                .addComponent(btBelum)
                                .addGap(0, 92, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idReceiveReport))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaPL))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tglMain))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btSudah)
                    .addComponent(btBelum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(simpan))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    new DashboardPegawai().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try{
            
            Connection con = (Connection)connect.configDB();
            String sql = "select No_Penjadwalan from penjadwalan where IDReceiveReport = '"+idReceiveReport.getText()+"'";
            PreparedStatement pstm = con.prepareStatement(sql);
            ResultSet rs=pstm.executeQuery();
            rs.next();
            int my_rqd_value = rs.getInt("No_Penjadwalan");
            String sql2;
            
            sql = "select No_IdentitasPL from pekerjalapangan where nama = '"+namaPL.getText()+"'";
            pstm = con.prepareStatement(sql);
            rs=pstm.executeQuery();
            rs.next();
            int id = rs.getInt("No_IdentitasPL");
            
            sql = "select ID_Customer from receivereport where ID_ReceiveReport = '"+idReceiveReport.getText()+"'";
            pstm = con.prepareStatement(sql);
            rs=pstm.executeQuery();
            rs.next();
            int idC = rs.getInt("ID_Customer");
         
            if (btSudah.isSelected()){
                sql = "INSERT INTO returnreport VALUES('"+idReceiveReport.getText()+"','"
                        +idC+"','"+my_rqd_value+"','"+id+"','"+tglMain.getText()+"','"+"Sudah Diperbaiki"+"')";
                pstm = con.prepareStatement(sql);
                pstm.execute();
                sql2 = "DELETE FROM penjadwalan WHERE IDReceiveReport = '"+idReceiveReport.getText()+"'";
                pstm = con.prepareStatement(sql2);
                pstm.execute();
                
            }else{
                sql = "INSERT INTO returnreport VALUES('"+idReceiveReport.getText()+"','"
                        +my_rqd_value+"','"+namaPL.getText()+"','"+tglMain.getText()+"','"+btBelum.isSelected()+"')";
                pstm = con.prepareStatement(sql);
                pstm.execute();
            }
            sql = "UPDATE tiang SET Status='Sudah Diperbaiki' WHERE Kode_Tiang=(Select Kode_Tiang FROM receivereport WHERE ID_ReceiveReport = '"+idReceiveReport.getText()+"')";
            pstm = con.prepareStatement(sql);
            pstm.execute();
            
            sql2 = "DELETE FROM receivereport WHERE ID_ReceiveReport = '"+idReceiveReport.getText()+"'";
            pstm = con.prepareStatement(sql2);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPerbaikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPerbaikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPerbaikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPerbaikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPerbaikan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btBelum;
    private javax.swing.JRadioButton btSudah;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel idReceiveReport;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel namaPL;
    private javax.swing.JButton simpan;
    public javax.swing.JLabel tglMain;
    // End of variables declaration//GEN-END:variables
}
